version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    env_file:
      - .env
    # volumes:
    #   - .:/code
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    db:
      driver: local
  # eble:
  #   image: efrecon/eble
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     - DATABASE=${DATA_BASE_HOST}
  #     - USER=${DATABASE_USER}
  #     - PASSWORD=${PASSWORD}
  #     - HOST=host.docker.internal
  #     - PORT=${DATA_BASE_PORT}
  #     - LOG_LEVEL=debug
  #   depends_on:
  #     - mysql
