INSERT INTO Amenity (description, title, icon) VALUES
('undefined', 'Internet', 'High-speed internet connection'),
('undefined', 'Air Conditioning', 'Air conditioning system'),
('undefined', 'Heating', 'Heating system'),
('undefined', 'Kitchen', 'Fully-equipped kitchen with appliances and cookware'),
('undefined', 'Washer and Dryer', 'In-unit washer and dryer'),
('undefined', 'Iron and Ironing Board', 'Iron and ironing board provided'),
('undefined', 'Hairdryer', 'Hairdryer provided'),
('undefined', 'Bed Linens and Towels', 'Bed linens and towels provided'),
('undefined', 'Television with Streaming Services', 'TV with streaming services available'),
('undefined', 'Work Desk and Chair', 'Work desk and chair provided'),
('undefined', 'Sofa and Coffee Table', 'Sofa and coffee table provided'),
('undefined', 'Dining Table and Chairs', 'Dining table and chairs provided'),
('undefined', 'Closet and Hangers', 'Closet and hangers provided'),
('undefined', 'Bathroom and Toiletries', 'Bathroom with shower and/or bathtub, toiletries provided'),
('undefined', 'Balcony or Terrace', 'Balcony or terrace available'),
('undefined', 'Fireplace', 'Fireplace provided'),
('undefined', 'Extra Bedding (Upon Request)', 'Extra bedding available upon request'),
('undefined', 'Smart Home Features', 'Smart home features available'),
('undefined', 'Gym Access', 'Access to a gym or fitness facility'),
('undefined', 'Sauna', 'Sauna available'),
('undefined', 'Jacuzzi or Hot Tub', 'Jacuzzi or hot tub available'),
('undefined', 'Pet-friendly Amenities', 'Pet-friendly amenities available (pet station, pet washing station)'),
('undefined', 'Garage Parking', 'Garage parking available'),
('undefined', 'Security System', 'Security system installed'),
('undefined', 'Concierge Service', 'Concierge service available'),
('undefined', 'Elevator Access', 'Access to an elevator'),
('undefined', 'Disabled Access Facilities', 'Facilities for disabled access available'),
('undefined', 'Private Pool', 'Private pool available'),
('undefined', 'Private Garden or Backyard', 'Private garden or backyard available')