INSERT INTO Transfer (type, flightNumber, nameOfSignage, guests, amountBags, phone, city,  time, comments, status, isArchived, notes,date, price, discount, bookingId, customerId) VALUES 
('departure', 'Alex', 'Veum Adam', 0, 1, '4', 'Lake Kathrynville', '2024-12-03', 'Caelum demum audeo tamisium.', 0, 0, 'Demonstro cultellus auctor tenuis quae argentum numquam appono usque adstringo conscendo vere defero aggredior desino cena caecus nostrum cupressus spargo.', '2024-08-28', 1, 1, 140, 1),
('arrival', 'Arden', 'Labadie Janet', 1, 0, '1', 'Wellington', '2024-07-07', 'Aggredior argentum facere theatrum.', 0, 0, 'Tribuo thema ventus capillus cauda carcer subseco subiungo temperantia labore ascit vetus est suspendo adhuc optio capto amplexus strues facere.', '2024-09-20', 1, 1, 139, 0),
('departure', 'Kyle', 'Emard Beatrice', 1, 0, '7', 'Victoria', '2024-05-31', 'Decretum verbum viriliter thema.', 0, 0, 'Trucido agnitio cuius aurum aut explicabo carus adflicto cupiditate cometes audax currus titulus ipsum cornu decet adiuvo vergo canonicus appello.', '2025-01-21', 1, 0, 141, 1),
('departure', 'Jamie', 'Altenwerth-Olson Vance', 0, 1, '3', 'Watersport', '2024-06-03', 'Terreo sperno sol strues.', 0, 0, 'Aqua temperantia demitto spiculum alius error in teres verto vomer vinco peccatus tolero accendo alius sufficio arx decimus terminatio pariatur.', '2025-03-19', 0, 1, 148, 0),
('arrival', 'Angel', 'Strosin Chadd', 1, 1, '0', 'Bartellview', '2024-11-20', 'Curia capillus corroboro suasoria.', 0, 0, 'Tonsor succurro adhaero vinco conduco vociferor tenax debeo ciminatio tutis currus creptio perspiciatis curia cotidie advenio sunt tandem cubitum arguo.', '2024-07-04', 0, 0, 142, 0),
('departure', 'Kai', 'Miller Dovie', 1, 1, '1', 'Pensacola', '2025-01-06', 'Comptus suppellex adicio vindico.', 0, 0, 'Aetas socius audeo sui abeo calco colligo vir vaco audacia peccatus argumentum videlicet causa nam auxilium urbanus aer cunabula caute.', '2024-10-30', 0, 0, 141, 1),
('departure', 'Addison', 'Lemke Reva', 1, 1, '1', 'Carrollfurt', '2025-01-01', 'Nobis vulgus videlicet suppellex.', 0, 0, 'Asporto varietas cohors in culpa attollo crastinus advoco sol demulceo auditor utique chirographum nisi aestas angelus alias statua somnus cometes.', '2024-11-16', 0, 1, 147, 0),
('departure', 'Charlie', 'Towne Lauretta', 0, 1, '0', 'Lake Autumnport', '2024-10-18', 'Undique attero demoror confugo.', 0, 0, 'Altus absque utrum apostolus demens conitor suppellex altus patruus nam carus sperno doloribus aperio conqueror nisi dolorum amplus statim repellendus.', '2024-08-07', 0, 0, 144, 0),
('departure', 'Jaden', 'Jones Melissa', 1, 1, '9', 'New Jordyn', '2024-08-31', 'Apud approbo torqueo taedium.', 0, 0, 'Vapulus tempora talio contabesco catena repellat tredecim deduco itaque textor magni animi vilitas cauda atrox assentator quod tertius officiis textilis.', '2025-04-18', 0, 0, 141, 0),
('departure', 'Kendall', 'Stehr Gracie', 1, 1, '7', 'Rancho Cucamonga', '2025-02-24', 'Depereo cribro alius fuga.', 0, 0, 'Suscipio vinculum sufficio cotidie deorsum confugo tolero cinis depopulo animadverto suscipio accommodo degenero cibo audio explicabo occaecati apud coepi volubilis.', '2024-09-18', 1, 0, 144, 1);