INSERT INTO Transfer (type, flightNumber, nameOfSignage, guests, amountBags, phone, city,  time, comments, status, isArchived, notes,date, price, discount, bookingId, customerId) VALUES 
('arrival', 'Sage', 'Nader Abdul', 1, 1, '1', 'Milwaukee', '2025-03-13', 'Torrens accommodo aetas volubilis.', 0, 0, 'Itaque arguo verbera cultellus suasoria aduro doloremque spoliatio vesper centum crebro defetiscor somnus certe bellum torqueo umerus solutio vitium tollo.', '2025-04-11', 1, 1, 3, 0),
('departure', 'Nico', 'Brown Vickie', 0, 0, '5', 'Hortenseberg', '2025-03-10', 'Capillus tenuis certus attollo.', 0, 0, 'Verecundia campana socius aiunt comitatus ars terebro quaerat apud infit cicuta convoco curatio doloribus crebro vestrum magni aegrotatio amet vobis.', '2024-12-21', 0, 0, 5, 1),
('departure', 'Finley', 'Monahan Nadia', 1, 1, '6', 'Hoppeshire', '2024-10-27', 'Adstringo abstergo suppono calamitas.', 0, 0, 'Solium asporto demitto quo via voveo admoveo ait sum tener atrocitas veritas cimentarius peior ascit dapifer apto caveo tendo velum.', '2024-08-11', 1, 1, 4, 0),
('arrival', 'Drew', 'Quigley Benedict', 0, 1, '1', 'Joanyside', '2025-01-07', 'Collum facere absconditus totus.', 0, 0, 'Damnatio spargo acerbitas adulatio deporto tergum congregatio defaeco ambulo tabella cum votum angelus voluptate curiositas acsi testimonium apostolus sono suffragium.', '2024-05-30', 0, 0, 9, 0),
('departure', 'Reign', 'Runolfsson Stacy', 1, 1, '3', 'New Marleeport', '2025-04-10', 'Adimpleo ipsum conventus utroque.', 0, 0, 'Vilis tres aequitas tametsi ultra vomica autem tero mollitia defendo conspergo velociter solio verbera tam surculus viridis brevis vinum ultra.', '2025-05-03', 0, 1, 7, 1),
('departure', 'Arden', 'Friesen Barbara', 1, 0, '8', 'Hollywood', '2025-03-14', 'Depopulo tonsor assentator vito.', 0, 0, 'Admiratio aequus venustas cimentarius cruciamentum ultio tardus cogo amiculum astrum iure calco ulterius commodo celebrer baiulus cubitum alii nulla utrimque.', '2024-11-03', 1, 0, 2, 0),
('departure', 'Leslie', 'Williamson Milton', 1, 0, '0', 'Ziemeboro', '2024-06-12', 'Vita trucido sequi copiose.', 0, 0, 'Tricesimus adicio utique consuasor surculus uredo creptio consequatur suggero coepi solus via cresco id animus speculum numquam solium molestias vetus.', '2025-04-25', 0, 0, 6, 1),
('departure', 'Avery', 'Gutkowski Tyler', 1, 0, '6', 'Murrayville', '2024-07-09', 'Desolo acquiro acer velut.', 0, 0, 'Valetudo curia ter antea undique vacuus commodo ventito vetus desipio porro animi cibo supra desparatus defluo audeo ancilla verumtamen stella.', '2024-09-29', 1, 1, 10, 1),
('departure', 'Nico', 'Bruen-Botsford Ricardo', 0, 0, '2', 'San Leandro', '2024-06-27', 'Cumque collum ullus universe.', 0, 0, 'Vesco minima demoror balbus admoneo benigne expedita aspernatur quam suppellex adsum arcus alius commodi versus antepono cerno totus cohaero contigo.', '2025-04-08', 0, 1, 1, 1),
('arrival', 'Shiloh', 'Ondricka Kayden', 1, 1, '9', 'Amymouth', '2025-03-30', 'Suppellex toties pariatur auxilium.', 0, 0, 'Acidus perspiciatis dicta canonicus explicabo atqui charisma undique tolero surgo adflicto caries tempora villa vigilo ustulo voluptas debitis benigne tredecim.', '2024-09-27', 1, 0, 7, 1);