INSERT INTO Amenity (translations, icon) VALUES
('{"en":{"title":"Air conditioning","description":"Air conditioning"},"ru":{"title":"кондиционер","description":"кондиционер"}}', 'Air conditioning'),
('{"en":{"title":"Bed linen","description":"Bed linen"},"ru":{"title":"постельное белье","description":"постельное белье"}}', 'Bed linen'),
('{"en":{"title":"Black-out blinds","description":"Black-out blinds"},"ru":{"title":"затемняющие шторы","description":"затемняющие шторы"}}', 'Black-out blinds'),
('{"en":{"title":"Body soap","description":"Body soap"},"ru":{"title":"жидкое мыло","description":"жидкое мыло"}}', 'Body soap'),
('{"en":{"title":"Cooking basics","description":"Cooking basics"},"ru":{"title":"основы приготовления пищи","description":"основы приготовления пищи"}}', 'Cooking basics'),
('{"en":{"title":"Pots and pans, oil, salt and pepper","description":"Pots and pans, oil, salt and pepper"},"ru":{"title":"кастрюли и сковороды, масло, соль и перец","description":"кастрюли и сковороды, масло, соль и перец"}}', 'Pots and pans, oil, salt and pepper'),
('{"en":{"title":"Dining table","description":"Dining table"},"ru":{"title":"обеденный стол","description":"обеденный стол"}}', 'Dining table'),
('{"en":{"title":"Dishes and cutlery","description":"Dishes and cutlery"},"ru":{"title":"посуда и столовые приборы","description":"посуда и столовые приборы"}}', 'Dishes and cutlery'),
('{"en":{"title":"Bowls, chopsticks, plates, cups, etc.","description":"Bowls, chopsticks, plates, cups, etc."},"ru":{"title":"миски, палочки для еды, тарелки, чашки и т.д.","description":"миски, палочки для еды, тарелки, чашки и т.д."}}', 'Bowls, chopsticks, plates, cups, etc.'),
('{"en":{"title":"Fire extinguisher","description":"Fire extinguisher"},"ru":{"title":"огнетушитель","description":"огнетушитель"}}', 'Fire extinguisher'),
('{"en":{"title":"Free parking","description":"Free parking"},"ru":{"title":"бесплатная парковка","description":"бесплатная парковка"}}', 'Free parking'),
('{"en":{"title":"Hair dryer","description":"Hair dryer"},"ru":{"title":"фен","description":"фен"}}', 'Hair dryer'),
('{"en":{"title":"Heating","description":"Heating"},"ru":{"title":"отопление","description":"отопление"}}', 'Heating'),
('{"en":{"title":"Hot water","description":"Hot water"},"ru":{"title":"горячая вода","description":"горячая вода"}}', 'Hot water'),
('{"en":{"title":"Hot water kettle","description":"Hot water kettle"},"ru":{"title":"чайник","description":"чайник"}}', 'Hot water kettle'),
('{"en":{"title":"Iron","description":"Iron"},"ru":{"title":"утюг","description":"утюг"}}', 'Iron'),
('{"en":{"title":"Kitchen","description":"Kitchen"},"ru":{"title":"кухня","description":"кухня"}}', 'Kitchen'),
('{"en":{"title":"Kitchenette","description":"Kitchenette"},"ru":{"title":"мини-кухня","description":"мини-кухня"}}', 'Kitchenette'),
('{"en":{"title":"Microwave","description":"Microwave"},"ru":{"title":"микроволновая печь","description":"микроволновая печь"}}', 'Microwave'),
('{"en":{"title":"Outdoor dining area","description":"Outdoor dining area"},"ru":{"title":"зона для пикника","description":"зона для пикника"}}', 'Outdoor dining area'),
('{"en":{"title":"Outdoor shower","description":"Outdoor shower"},"ru":{"title":"уличный душ","description":"уличный душ"}}', 'Outdoor shower'),
('{"en":{"title":"Patio or balcony","description":"Patio or balcony"},"ru":{"title":"патио или балкон","description":"патио или балкон"}}', 'Patio or balcony'),
('{"en":{"title":"Pool","description":"Pool"},"ru":{"title":"бассейн","description":"бассейн"}}', 'Pool'),
('{"en":{"title":"Refrigerator","description":"Refrigerator"},"ru":{"title":"холодильник","description":"холодильник"}}', 'Refrigerator'),
('{"en":{"title":"Shampoo","description":"Shampoo"},"ru":{"title":"шампунь","description":"шампунь"}}', 'Shampoo'),
('{"en":{"title":"Smoke alarm","description":"Smoke alarm"},"ru":{"title":"дымовой датчик","description":"дымовой датчик"}}', 'Smoke alarm'),
('{"en":{"title":"Stove","description":"Stove"},"ru":{"title":"плита","description":"плита"}}', 'Stove'),
('{"en":{"title":"Toaster","description":"Toaster"},"ru":{"title":"тостер","description":"тостер"}}', 'Toaster'),
('{"en":{"title":"TV","description":"TV"},"ru":{"title":"телевизор","description":"телевизор"}}', 'TV'),
('{"en":{"title":"Washing machine","description":"Washing machine"},"ru":{"title":"стиральная машина","description":"стиральная машина"}}', 'Washing machine'),
('{"en":{"title":"Wi-Fi","description":"Wi-Fi"},"ru":{"title":"Wi-Fi","description":"Wi-Fi"}}', 'Wi-Fi')