INSERT INTO ComplexServices (description, title, icon, price) VALUES
("Elevator", "Elevator", "Elevator in the building", "10"),
("Parking (covered or uncovered)", "Parking", "Parking available (covered or uncovered)", "15"),
("Gym and fitness center", "Gym and Fitness Center", "Gym and fitness center available", "20"),
("Pool and hot tub", "Pool and Hot Tub", "Pool and hot tub available", "25"),
("Rooftop terrace or garden", "Rooftop Terrace or Garden", "Rooftop terrace or garden available", "10"),
("BBQ area", "BBQ Area", "BBQ area available", "15"),
("Business center", "Business Center", "Business center available", "30"),
("Lounge or community room", "Lounge or Community Room", "Lounge or community room available", "10"),
("Bike storage", "Bike Storage", "Bike storage available", "5"),
("Security system and cameras", "Security System and Cameras", "Security system and cameras installed", "10"),
("On-site maintenance and management", "Maintenance and Management", "On-site maintenance and management available", "20"),
("Pet-friendly amenities (pet station, pet washing station)", "Pet-friendly Amenities", "Pet-friendly amenities available (pet station, pet washing station)", "5"),
("Conference facilities", "Conference Facilities", "Conference facilities available", "50"),
("Laundry service", "Laundry Service", "Laundry service available", "10"),
("Housekeeping service", "Housekeeping Service", "Housekeeping service available", "20"),
("Shuttle service", "Shuttle Service", "Shuttle service available", "15"),
("On-site restaurant or bar", "Restaurant or Bar", "On-site restaurant or bar available", "25"),
("Children's play area", "Children's Play Area", "Children's play area available", "5"),
("Library", "Library", "Library available", "5"),
("Car rental service", "Car Rental Service", "Car rental service available", "30"),
("Spa", "Spa", "Spa available", "40"),
("Beach access", "Beach Access", "Beach access available", "20"),
("Ski storage", "Ski Storage", "Ski storage available", "10"),
("24-hour reception", "24-hour Reception", "24-hour reception available", "5"),
("Tour desk", "Tour Desk", "Tour desk available", "5"),
("Airport transportation", "Airport Transportation", "Airport transportation available", "50"),
("Vending machines", "Vending Machines", "Vending machines available", "5"),
("ATM", "ATM", "ATM available", "5"),
("Currency exchange", "Currency Exchange", "Currency exchange available", "5")