INSERT INTO Amenity (description, title, icon) VALUES
('High-speed internet', 'Internet', 'High-speed internet connection'),
('Air conditioning', 'Air Conditioning', 'Air conditioning system'),
('Heating', 'Heating', 'Heating system'),
('Fully-equipped kitchen (refrigerator, oven, stove, microwave, dishwasher, coffee maker, toaster, cookware, and dishware)', 'Kitchen', 'Fully-equipped kitchen with appliances and cookware'),
('Washer and dryer', 'Washer and Dryer', 'In-unit washer and dryer'),
('Iron and ironing board', 'Iron and Ironing Board', 'Iron and ironing board provided'),
('Hairdryer', 'Hairdryer', 'Hairdryer provided'),
('Bed linens and towels', 'Bed Linens and Towels', 'Bed linens and towels provided'),
('Television with streaming services', 'Television with Streaming Services', 'TV with streaming services available'),
('Work desk and chair', 'Work Desk and Chair', 'Work desk and chair provided'),
('Sofa and coffee table', 'Sofa and Coffee Table', 'Sofa and coffee table provided'),
('Dining table and chairs', 'Dining Table and Chairs', 'Dining table and chairs provided'),
('Closet and hangers', 'Closet and Hangers', 'Closet and hangers provided'),
('Bathroom with shower and/or bathtub, Toiletries (shampoo, conditioner, body wash, and hand soap)', 'Bathroom and Toiletries', 'Bathroom with shower and/or bathtub, toiletries provided'),
('Balcony or terrace', 'Balcony or Terrace', 'Balcony or terrace available'),
('Fireplace', 'Fireplace', 'Fireplace provided'),
('Extra bedding (upon request)', 'Extra Bedding (Upon Request)', 'Extra bedding available upon request'),
('Smart home features (such as smart locks or thermostats)', 'Smart Home Features', 'Smart home features available'),
('Access to a gym or fitness facility', 'Gym Access', 'Access to a gym or fitness facility'),
('Sauna', 'Sauna', 'Sauna available'),
('Jacuzzi or hot tub', 'Jacuzzi or Hot Tub', 'Jacuzzi or hot tub available'),
('Pet-friendly amenities (pet station, pet washing station)', 'Pet-friendly Amenities', 'Pet-friendly amenities available (pet station, pet washing station)'),
('Garage parking', 'Garage Parking', 'Garage parking available'),
('Security system', 'Security System', 'Security system installed'),
('Concierge service', 'Concierge Service', 'Concierge service available'),
('Access to an elevator', 'Elevator Access', 'Access to an elevator'),
('Disabled access facilities', 'Disabled Access Facilities', 'Facilities for disabled access available'),
('Private pool', 'Private Pool', 'Private pool available'),
('Private garden or backyard', 'Private Garden or Backyard', 'Private garden or backyard available')