INSERT INTO Amenity (description, title, icon) VALUES
('High-speed internet connection', 'Internet', 'High-speed internet'),
('Air conditioning system', 'Air Conditioning', 'Air conditioning'),
('Heating system', 'Heating', 'Heating'),
('Fully-equipped kitchen with appliances and cookware', 'Kitchen', 'Fully-equipped kitchen (refrigerator, oven, stove, microwave, dishwasher, coffee maker, toaster, cookware, and dishware)'),
('In-unit washer and dryer', 'Washer and Dryer', 'Washer and dryer'),
('Iron and ironing board provided', 'Iron and Ironing Board', 'Iron and ironing board'),
('Hairdryer provided', 'Hairdryer', 'Hairdryer'),
('Bed linens and towels provided', 'Bed Linens and Towels', 'Bed linens and towels'),
('TV with streaming services available', 'Television with Streaming Services', 'Television with streaming services'),
('Work desk and chair provided', 'Work Desk and Chair', 'Work desk and chair'),
('Sofa and coffee table provided', 'Sofa and Coffee Table', 'Sofa and coffee table'),
('Dining table and chairs provided', 'Dining Table and Chairs', 'Dining table and chairs'),
('Closet and hangers provided', 'Closet and Hangers', 'Closet and hangers'),
('Bathroom with shower and/or bathtub, toiletries provided', 'Bathroom and Toiletries', 'Bathroom with shower and/or bathtub, Toiletries (shampoo, conditioner, body wash, and hand soap)'),
('Balcony or terrace available', 'Balcony or Terrace', 'Balcony or terrace'),
('Fireplace provided', 'Fireplace', 'Fireplace'),
('Extra bedding available upon request', 'Extra Bedding (Upon Request)', 'Extra bedding (upon request)'),
('Smart home features available', 'Smart Home Features', 'Smart home features (such as smart locks or thermostats)'),
('Access to a gym or fitness facility', 'Gym Access', 'Access to a gym or fitness facility'),
('Sauna available', 'Sauna', 'Sauna'),
('Jacuzzi or hot tub available', 'Jacuzzi or Hot Tub', 'Jacuzzi or hot tub'),
('Pet-friendly amenities available (pet station, pet washing station)', 'Pet-friendly Amenities', 'Pet-friendly amenities (pet station, pet washing station)'),
('Garage parking available', 'Garage Parking', 'Garage parking'),
('Security system installed', 'Security System', 'Security system'),
('Concierge service available', 'Concierge Service', 'Concierge service'),
('Access to an elevator', 'Elevator Access', 'Access to an elevator'),
('Facilities for disabled access available', 'Disabled Access Facilities', 'Disabled access facilities'),
('Private pool available', 'Private Pool', 'Private pool'),
('Private garden or backyard available', 'Private Garden or Backyard', 'Private garden or backyard')