INSERT INTO Amenity (translations, icon) VALUES
('{"en":{"title":"Air conditioning","description":"Air conditioning"},"ru":{"title":"кондиционер","description":"кондиционер"}}', 'https://astayhome.com/assets/icons/amenities/Air%20conditioning.png'),
('{"en":{"title":"Bed linen","description":"Bed linen"},"ru":{"title":"постельное белье","description":"постельное белье"}}', 'https://astayhome.com/assets/icons/amenities/Bed%20linen.png'),
('{"en":{"title":"Black-out blinds","description":"Black-out blinds"},"ru":{"title":"затемняющие шторы","description":"затемняющие шторы"}}', 'https://astayhome.com/assets/icons/amenities/Black-out%20blinds.png'),
('{"en":{"title":"Body soap","description":"Body soap"},"ru":{"title":"жидкое мыло","description":"жидкое мыло"}}', 'https://astayhome.com/assets/icons/amenities/Body%20soap.png'),
('{"en":{"title":"Cooking basics","description":"Cooking basics"},"ru":{"title":"основы приготовления пищи","description":"основы приготовления пищи"}}', 'https://astayhome.com/assets/icons/amenities/Cooking%20basics.png'),
('{"en":{"title":"Pots and pans, oil, salt and pepper","description":"Pots and pans, oil, salt and pepper"},"ru":{"title":"кастрюли и сковороды, масло, соль и перец","description":"кастрюли и сковороды, масло, соль и перец"}}', 'https://astayhome.com/assets/icons/amenities/Pots%20and%20pans,%20oil,%20salt%20and%20pepper.png'),
('{"en":{"title":"Dining table","description":"Dining table"},"ru":{"title":"обеденный стол","description":"обеденный стол"}}', 'https://astayhome.com/assets/icons/amenities/Dining%20table.png'),
('{"en":{"title":"Dishes and cutlery","description":"Dishes and cutlery"},"ru":{"title":"посуда и столовые приборы","description":"посуда и столовые приборы"}}', 'https://astayhome.com/assets/icons/amenities/Dishes%20and%20cutlery.png'),
('{"en":{"title":"Bowls, chopsticks, plates, cups, etc.","description":"Bowls, chopsticks, plates, cups, etc."},"ru":{"title":"миски, палочки для еды, тарелки, чашки и т.д.","description":"миски, палочки для еды, тарелки, чашки и т.д."}}', 'https://astayhome.com/assets/icons/amenities/Bowls,%20chopsticks,%20plates,%20cups,%20etc..png'),
('{"en":{"title":"Fire extinguisher","description":"Fire extinguisher"},"ru":{"title":"огнетушитель","description":"огнетушитель"}}', 'https://astayhome.com/assets/icons/amenities/Fire%20extinguisher.png'),
('{"en":{"title":"Free parking","description":"Free parking"},"ru":{"title":"бесплатная парковка","description":"бесплатная парковка"}}', 'https://astayhome.com/assets/icons/amenities/Free%20parking.png'),
('{"en":{"title":"Hair dryer","description":"Hair dryer"},"ru":{"title":"фен","description":"фен"}}', 'https://astayhome.com/assets/icons/amenities/Hair%20dryer.png'),
('{"en":{"title":"Heating","description":"Heating"},"ru":{"title":"отопление","description":"отопление"}}', 'https://astayhome.com/assets/icons/amenities/Heating.png'),
('{"en":{"title":"Hot water","description":"Hot water"},"ru":{"title":"горячая вода","description":"горячая вода"}}', 'https://astayhome.com/assets/icons/amenities/Hot%20water.png'),
('{"en":{"title":"Hot water kettle","description":"Hot water kettle"},"ru":{"title":"чайник","description":"чайник"}}', 'https://astayhome.com/assets/icons/amenities/Hot%20water%20kettle.png'),
('{"en":{"title":"Iron","description":"Iron"},"ru":{"title":"утюг","description":"утюг"}}', 'https://astayhome.com/assets/icons/amenities/Iron.png'),
('{"en":{"title":"Kitchen","description":"Kitchen"},"ru":{"title":"кухня","description":"кухня"}}', 'https://astayhome.com/assets/icons/amenities/Kitchen.png'),
('{"en":{"title":"Kitchenette","description":"Kitchenette"},"ru":{"title":"мини-кухня","description":"мини-кухня"}}', 'https://astayhome.com/assets/icons/amenities/Kitchenette.png'),
('{"en":{"title":"Microwave","description":"Microwave"},"ru":{"title":"микроволновая печь","description":"микроволновая печь"}}', 'https://astayhome.com/assets/icons/amenities/Microwave.png'),
('{"en":{"title":"Outdoor dining area","description":"Outdoor dining area"},"ru":{"title":"зона для пикника","description":"зона для пикника"}}', 'https://astayhome.com/assets/icons/amenities/Outdoor%20dining%20area.png'),
('{"en":{"title":"Outdoor shower","description":"Outdoor shower"},"ru":{"title":"уличный душ","description":"уличный душ"}}', 'https://astayhome.com/assets/icons/amenities/Outdoor%20shower.png'),
('{"en":{"title":"Patio or balcony","description":"Patio or balcony"},"ru":{"title":"патио или балкон","description":"патио или балкон"}}', 'https://astayhome.com/assets/icons/amenities/Patio%20or%20balcony.png'),
('{"en":{"title":"Pool","description":"Pool"},"ru":{"title":"бассейн","description":"бассейн"}}', 'https://astayhome.com/assets/icons/amenities/Pool.png'),
('{"en":{"title":"Refrigerator","description":"Refrigerator"},"ru":{"title":"холодильник","description":"холодильник"}}', 'https://astayhome.com/assets/icons/amenities/Refrigerator.png'),
('{"en":{"title":"Shampoo","description":"Shampoo"},"ru":{"title":"шампунь","description":"шампунь"}}', 'https://astayhome.com/assets/icons/amenities/Shampoo.png'),
('{"en":{"title":"Smoke alarm","description":"Smoke alarm"},"ru":{"title":"дымовой датчик","description":"дымовой датчик"}}', 'https://astayhome.com/assets/icons/amenities/Smoke%20alarm.png'),
('{"en":{"title":"Stove","description":"Stove"},"ru":{"title":"плита","description":"плита"}}', 'https://astayhome.com/assets/icons/amenities/Stove.png'),
('{"en":{"title":"Toaster","description":"Toaster"},"ru":{"title":"тостер","description":"тостер"}}', 'https://astayhome.com/assets/icons/amenities/Toaster.png'),
('{"en":{"title":"TV","description":"TV"},"ru":{"title":"телевизор","description":"телевизор"}}', 'https://astayhome.com/assets/icons/amenities/TV.png'),
('{"en":{"title":"Washing machine","description":"Washing machine"},"ru":{"title":"стиральная машина","description":"стиральная машина"}}', 'https://astayhome.com/assets/icons/amenities/Washing%20machine.png'),
('{"en":{"title":"Wi-Fi","description":"Wi-Fi"},"ru":{"title":"Wi-Fi","description":"Wi-Fi"}}', 'https://astayhome.com/assets/icons/amenities/Wi-Fi.png')